#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    site_name: 'The Task'
    design:
        menu:
            - { label: 'Home', url: '/', rel: 'index' }
            - { entity: 'SArticles', label: 'Artikles' }
            - { entity: 'SCategories', label: 'Kategorien' }
            - { entity: 'SArtcatRelationships', label: 'Relations' }
            - { label: 'Neues Artikle', route: 'new_registration'}
            - { label: 'Neues Kategory', route: 'newcat_registration'}
    entities:
        SArticles:
            class: App\Entity\SArticles
            disabled_actions: ['new']
        SCategories:
            class: App\Entity\SCategories
            disabled_actions: ['new']
        SArtcatRelationships:
            class: App\Entity\SArtcatRelationships
            disabled_actions: ['new']