<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxOX2gs\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxOX2gs/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSxOX2gs.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerSxOX2gs\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerSxOX2gs\srcProdProjectContainer(array(
    'container.build_hash' => 'SxOX2gs',
    'container.build_id' => 'f1182707',
    'container.build_time' => 1530275599,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxOX2gs');
