<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV2eU2tB\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV2eU2tB/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerV2eU2tB.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerV2eU2tB\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerV2eU2tB\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'V2eU2tB',
    'container.build_id' => '99dffc8e',
    'container.build_time' => 1527167727,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerV2eU2tB');
