<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE8QhGnR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE8QhGnR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE8QhGnR.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerE8QhGnR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerE8QhGnR\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'E8QhGnR',
    'container.build_id' => 'd639aaa7',
    'container.build_time' => 1530276513,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerE8QhGnR');
