<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV62tT3h\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV62tT3h/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerV62tT3h.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerV62tT3h\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerV62tT3h\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'V62tT3h',
    'container.build_id' => '03ba450d',
    'container.build_time' => 1527117112,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerV62tT3h');
