<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easyadmin.cache.config_warmer' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Cache/ConfigWarmer.php';

return $this->privates['easyadmin.cache.config_warmer'] = new \EasyCorp\Bundle\EasyAdminBundle\Cache\ConfigWarmer(($this->services['easyadmin.config.manager'] ?? $this->getEasyadmin_Config_ManagerService()));
